import Head from "next/head";
import Image from "next/image";
import Channel from "../components/channel";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>nnk kid tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <a
          href="https://www.paypal.com/donate/?hosted_button_id=RXEDTFXRB6EQW"
          className="donate"
        >
          Donate Me
        </a>
        <div className={styles.main}>
          <Channel name="channel 1" />
          <Channel name="channel 2" />
          <Channel name="channel 3" />
        </div>
      </div>
    </div>
  );
}
