import Head from "next/head";
import Image from "next/image";
import Channel from "../components/channel";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>nnk kid tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Channel name="ch1" />
        <Channel name="ch2" />
        <Channel name="ch3" />
      </div>
    </div>
  );
}
